apiVersion: apps/v1
kind: ReplicaSet
metadata:
      name: webappreplicaset3
      labels:
          app: webappreplicaset3

spec:
    replicas: 3
    template: 
              metadata:  #like a tag
                      name: webappreplicaset3
                      labels:
                        app: webappreplicaset3
              spec:
                 containers:
                    - name: mypod-cont1
                      image: nginx:latest
                      resources: 
                          requests:
                            cpu: "50m"
                            memory: "100Mi"        
                      ports:  
                        - name: http
                          containerPort: 80
                          protocol: TCP

    selector:
            matchExpressions:
                         - {key: app , operator: NotIn , values: [webappreplicaset , webappreplicaset2]}                    