
apiVersion: v1
kind:  ReplicationController
metadata: 
       name: webappreplica
       labels:
            app: webappreplica
spec: 
    replicas: 3  
    template:
      metadata:  
         labels: 
            app: webappreplica
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector:
          app: webappreplica

