
apiVersion: apps/v1 
kind: DaemonSet 
metadata:
        name: daemonst
        labels: 
              app: daemonst
spec:
     selector:
           matchLabels:
                app: daemonst    
     template:
          metadata:  
              labels: 
                  app: daemonst
          spec:
            containers:
                - name: mypod-cont1
                  image: nginx:latest
                  resources: 
                      requests:
                        cpu: "50m"
                        memory: "90Mi"        
                  ports:  
                    - name: http
                      containerPort: 80
                      protocol: TCP            
